version: "3.8"

services:

  database-cont:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    container_name: database-cont


  backend-cont:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    container_name: backend-cont
    depends_on:
      - database-cont


  frontend-cont:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    container_name: frontend-cont
    
    depends_on:
      - backend-cont
volumes:
  data:
  logs: